name: datadosth_app
description: DATA DOSTH - Location based
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  geolocator: 10.1.0
  geocoding: 2.1.1
flutter:
  uses-material-design: true
