name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'
          cache: true

      - name: Fix Project Correctly (Without Deleting Your Code)
        run: |
          sed -i 's/name: datadosth-app/name: datadosth_app/' pubspec.yaml
          cp -r lib lib_backup
          rm -rf android
          flutter create . --platforms=android --project-name datadosth_app
          rm -rf lib
          mv lib_backup lib
          flutter pub get

      - name: Build APK
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: datadosth-apk-real
          path: build/app/outputs/flutter-apk/app-debug.apk
