name: Build APK
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'
          channel: 'stable'
      - name: APK ni nirminchandi
        run: |
          flutter create --project-name datadosth_app --platforms=android . --overwrite
          flutter pub get
          flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: DATA-DOSTH-APK
          path: build/app/outputs/flutter-apk/app-release.apk
